blogs/urls.py
from . import views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from user.views import register as register_views
from user.views import profile as profile_views
from user.views import profile_update as profile_update_views
from django.contrib.auth import views as auth_views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.PostCreate.as_view(template_name='blogs/posts.html'), name='post'),
    path('posts/<int:pk>/', views.PostDetail.as_view(template_name='blogs/post_detail.html'),name='post-detail'),
    path('posts/<int:pk>/update', views.PostUpdate.as_view(template_name='blogs/posts.html'),name='post-update'),
    path('posts/<int:pk>/delete', views.PostDelete.as_view(template_name='blogs/post_delete.html'),name='post-delete'),
    path('leetcode/',views.leetcode, name='leetcode'),
    path('register/', register_views, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
    path('profile/<slug:slug>/',profile_views.as_view(),name='profile'),
    path('profile/<slug:slug>/update',profile_update_views, name='profile-update'),
    path('feedback/',views.FeedbackCreate.as_view(template_name='blogs/feedback.html'),name='feedback')

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
class Post(models.Model):
	
	pub_date = models.DateTimeField(default=timezone.now)

	title =  models.CharField(max_length=200)

	problem_num = models.IntegerField(
		default=1,
		validators=[
            MaxValueValidator(2000),
            MinValueValidator(1)
        ]
    )

	description = models.TextField(default="")

	content = models.TextField(default=" ",blank=True)

	url = models.URLField(max_length=200,default='https://leetcode.com/problemset/all/')

	user = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blogs:post-detail',kwargs={'pk':self.pk})

class Feedback(models.Model):

	pub_date = models.DateTimeField(default=timezone.now)

	title =  models.CharField(max_length=200)

	description = models.TextField()

	user = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return "Feedback:{title} by {user}".format(title = self.title, user = self.user)

	def get_absolute_url(self):
		return reverse('blogs:index')

blogs/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post
from django.utils.translation import ugettext_lazy as _

class BlogForm(ModelForm):

	class Meta:
		model = Post
		fields = ('title','problem_num','description','content','url')
		labels = {
            'content': _('Code'),
            'problem_num': _('Problem Number'),
        } 

blogs/views.py
from django.http import HttpResponse, HttpResponseRedirect
from pathlib import Path
from django.template import Context, loader
from django.shortcuts import get_object_or_404, render, reverse
from .models import Post, Feedback
from django.views.generic.edit import CreateView,UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import BlogForm
from django.views import View
# Create your views here.
def index(request):
	
	return HttpResponseRedirect(reverse('blogs:leetcode'))
	# return render(request, 'blogs/index.html',{'posts':posts})
def leetcode(request):

	latest_question_list = Post.objects.all()

	print(latest_question_list)

	return render(request, 'blogs/leetcode.html',{'latest_question_list':latest_question_list})


class PostDetail(DetailView):

	model = Post

class PostDelete(LoginRequiredMixin,UserPassesTestMixin, DeleteView):

	login_url = '/blogs/login/'

	redirect_field_name='blogs:login'

	model = Post

	success_url = '/'

	def test_func(self):
		return self.get_object().user==self.request.user

	def get_success_url(self):
	# Assuming there is a ForeignKey from Comment to Post in your model
		post = self.get_object()
		return reverse('blogs:leetcode')

class PostUpdate(LoginRequiredMixin,UserPassesTestMixin, UpdateView):

	login_url = '/blogs/login/'

	redirect_field_name='blogs:login'

	form_class = BlogForm
	
	model = Post

	#fields = ['title','description','code','url']

	def test_func(self):
		
		return self.get_object().user==self.request.user

	def form_valid(self,form):
		
		form.instance.user = self.request.user
		
		return super().form_valid(form)

	def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
		context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
		context['latest_question_list'] = [self.get_object()]
		context['path'] = Path(self.request.path).parent
		return context


class PostCreate(LoginRequiredMixin,CreateView):

	# print(request.path)

	login_url = '/blogs/login/'

	redirect_field_name='blogs:login'

	form_class = BlogForm
	# model = Post

	# fields = ['title','description','content','url']
	
	def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
		context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
		context['latest_question_list'] = Post.objects.all()
		context['path'] = Path(self.request.path).parent
		return context

	def form_valid(self,form):
		form.instance.user = self.request.user
		return super().form_valid(form)

class FeedbackCreate(LoginRequiredMixin,CreateView):

	login_url = '/blogs/login/'

	redirect_field_name='blogs:login'

	model = Feedback

	fields = ['title','description']

	def form_valid(self,form):
		form.instance.user = self.request.user
		return super().form_valid(form)

blogs/templates/blogs/feedback.html
{% extends "blogs/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
	<div class="mb-3">
		{% csrf_token %}

		{{ form | crispy}}

		<div class="input-group mb-3" style="margin-left: 15px;">
        	<input class="btn btn-outline-primary mb-3" type="submit">
        </div>
	</div>
</form>


{% endblock %}

blogs/templates/blogs/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Leetcode Discuss</title>
	<script src="{% static 'blogs/lib/codemirror.js' %}"></script>
	<link rel="stylesheet" href="{% static 'blogs/lib/codemirror.css' %}">
	<link rel="stylesheet" href="{% static 'blogs/style.css' %}">
	<script type="text/javascript" src="{% static 'blogs/main.js' %}"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>
<body style="background-color: #f5f5f5 !important">

	<div class="main-section" style="padding:10px;">
		<nav class="navbar navbar-expand-lg navbar-light bg-dark">
		  	<div class="container-fluid">
		    	<a class="navbar-brand" href="{% url 'blogs:index'%}" style="color: white">Leetcode Discuss</a>
		    		<!-- <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->
				      	<ul class="navbar-nav me-auto mb-2 mb-lg-0" style="flex-direction: row;">
				        	{% if user.is_authenticated %}
				  				<li class="nav-item"><a href="{% url 'blogs:logout' %}?next={{request.path}}"><button type="button" id="logout_btn" class="btn btn-outline-light me-md-2" >Log out</button></a></li>
				  				<li class="nav-item"><a href="{% url 'blogs:profile' user.username %}?next={{request.path}}"><button type="button" id="logout_btn" class="btn btn-outline-light me-md-2" >Profile</button></a></li>
				  				<li class="nav-item"><a href="{% url 'blogs:post' %}?next={{request.path}}"><button type="button" id="post_btn" class="btn btn-outline-light me-md-2">Post</button></a></li>
			  				{% else %}
			  					<li class="nav-item"><a href="{% url 'blogs:register' %}"><button type="button" id="reg_btn" class="btn btn-outline-light me-md-2" >Register</button></a></li>
			  					<li class="nav-item"><a href="{% url 'blogs:login' %}"><button type="button" id="sign_btn" class="btn btn-outline-light me-md-2" >Sign In</button></a></li>
			  					<li class="nav-item"><a href="{% url 'blogs:post' %}?next={{request.path}}"><button type="button" id="post_btn" class="btn btn-outline-light me-md-2">Post</button></a></li>
			  				{% endif %}
				      	</ul>
		    		<!-- </div> -->
		    	{% block modal %}{% endblock %}
		  </div>
		</nav>
	</div>

	<div class="container-xl" style="display: flex;flex-direction: row;min-height: 1000px;">

		<div class="main-section">
			{% block content %}{% endblock %}
		</div>
		
		<!-- <div class="sidebar">
			

		</div>
 -->

	</div>
	<div>
</body>
</html>

blogs/templates/blogs/leetcode.html
{% extends "blogs/index.html" %}

{% block content %}
<div class="blogs-wrapper" style="display: flex;flex-direction: row;">
	
	<CardGroup class="cardContainer" style="width: 70%">
	{% for question in latest_question_list %}
		<div class="card mb-3" style="margin-bottom: 15px;border: unset;border-radius: unset;">
		  	<div class="row g-0">
			  	<div class="col-md-4" style="max-width: 80px;background-color: #f5f5f5 !important;padding-right:15px;">
		      		<a href="{% url 'blogs:profile' question.user.username %}"><img class="img-thumbnail" style="height: 40%;width: 100%;" src="{{ question.user.profile.image.url }}"></a>
		    	</div>
		    	<div class="col-md-10">
			    	<div class="card-header" style="background-color: white">
				    	Leetcode Problem #{{question.problem_num}}
				  	</div>
				  	<div class="card-body">
				    	<a href="{% url 'blogs:post-detail' question.id %}"><h5 class="card-title">{{question.title}}</h5></a>
				    	<a href="{{question.url}}" class="btn btn-outline-dark" target="_blank">Check out this problem</a>
				  	</div>
				  	<div class="card-footer text-muted" style="background-color: white;display: flex;">
			    		posted by: <div><a href="{% url 'blogs:profile' question.user.username %}"><img src="{{ question.user.profile.image.url}}" style="width: 15px;height: 20px;"></a>{{question.user.username}}  </div> &nbsp created at: {{question.pub_date}}
			  		</div>
			  	</div>
		  	</div> 	
		</div>
	{% endfor %}
	</CardGroup>

	<div class="card" style="width: 30%;height: fit-content;margin: 20px;">
	  <div class="card-header">
	    Featured
	  </div>
	  <ul class="list-group list-group-flush">
	    <a class="list-group-item list-group-item-action" href="https://leetcode.com/problemset/all/" target="_blank">Go Practice Now!</a>
	    <a class="list-group-item list-group-item-action" href="{% url 'blogs:feedback' %}">Give Us Feedback</a>
	  </ul>
	</div>

</div>
{% endblock %}

blogs/templates/blogs/post_delete.html
{% extends "blogs/index.html" %}

{% load crispy_forms_tags %}

{% block content %}
<form method="POST">
	{% csrf_token %}
	<div class="mb-3 row">
    	<label for="exampleFormControlInput1" class="form-label"><p>Are you sure you want to delete "{{ object }}"?</p></label>
    	
	</div><input class="btn btn-outline-primary mb-3" type="submit">
</form>
{% endblock content %}

blogs/templates/blogs/post_detail.html
{% extends "blogs/index.html" %}

{% block content %}

<div class="card mb-3">
	
	    
	   
			<div class="card" style="margin: 15px;">
			  	<div class="card-header" style="background-color: white">
			    	<a href="{{object.url}}" target="_blank">Leetcode Problem #{{object.problem_num}}</a>
			  	</div>
			  	<div class="card-body">

			    	<h3 class="card-title" style="font-weight: bold;">{{object.title}}</h3>
			   
			    	<p class="card-text" style="font-size: 15px;">{{object.description}}</p>
			    	<p class="card-text" style="font-size: 15px;"><textarea class="code-content">{{object.content}}</textarea></p>
			    	
			    	
			  	</div>
			  	<div class="card-footer text-muted" style="background-color: white;display: flex;">
					posted by:<div><a href="{% url 'blogs:profile' object.user.username%}"><img src="{{ object.user.profile.image.url}}" style="width: 15px;height: 20px;"></a>
					{{object.user.username}}</div> &nbsp created at: {{object.pub_date}}
				</div>
				<div class="card-footer">
				{% if object.user.username == request.user.username %}
					<a href="{{object.url}}" class="btn btn-outline-primary">Check out this problem</a>
					<a href="{% url 'blogs:post-update' object.id %}" class="btn btn-outline-secondary">Update</a>
					<a href="{% url 'blogs:post-delete' object.id %}" class="btn btn-outline-danger">Delete</a>
				{% endif %}
				</div>
			</div>
	
  	
</div>

{% endblock %}

blogs/templates/blogs/posts.html
{% extends "blogs/leetcode.html" %}

{% load crispy_forms_tags %}

{% block modal %}
<div class="modal" style="display: block;">
  <div class="modal-dialog modal-dialog-scrollable" style="min-width: 800px;">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">What would you like to post?</h5>
        <a href="{{path}}"><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></a>
      </div>
      <div class="modal-body">
        <form action="" method="post" id="post_form">
        	<div class="mb-3">
				{% csrf_token %}

				{{ form | crispy}}

				<div class="input-group mb-3" style="margin-left: 15px;">
          <input class="btn btn-outline-primary mb-3" type="submit">
        </div>
			</div>
		</form>
      </div>
    </div>
  </div>
</div>
{% endblock %}