blogs/urls.py
from . import views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from user.views import register as register_views
from user.views import profile as profile_views
from user.views import profile_update as profile_update_views
from django.contrib.auth import views as auth_views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.PostCreate.as_view(template_name='blogs/posts.html'), name='post'),
    path('posts/<int:pk>/', views.PostDetail.as_view(template_name='blogs/post_detail.html'),name='post-detail'),
    path('posts/<int:pk>/update', views.PostUpdate.as_view(template_name='blogs/posts.html'),name='post-update'),
    path('posts/<int:pk>/delete', views.PostDelete.as_view(template_name='blogs/post_delete.html'),name='post-delete'),
    path('leetcode/',views.leetcode, name='leetcode'),
    path('register/', register_views, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
    path('profile/<slug:slug>/',profile_views.as_view(),name='profile'),
    path('profile/<slug:slug>/update',profile_update_views, name='profile-update'),
    path('feedback/',views.FeedbackCreate.as_view(template_name='blogs/feedback.html'),name='feedback')

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls')),
]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default='default.jpg', upload_to='profile_pics')

	def __str__(self):
		return f'{self.user.username} Profile'

	def save(self, *args, **kwargs):
		super(Profile, self).save(*args, **kwargs)

		img = Image.open(self.image.path)

		if img.height>300 or img.width>300:
			output_size = (300,300)
			img.thumbnail(output_size)
			img.save(self.image.path)

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile



class registerForm(UserCreationForm):

	email = forms.EmailField()

	class Meta:
		model = User
		fields= ('username','email','password1','password2')

class UserUpdateForm(forms.ModelForm):

	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['email']

class ProfileUpdateForm(forms.ModelForm):

	class Meta:
		model = Profile
		fields = ['image']
			
		
			

user/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, reverse
from .forms import registerForm, UserUpdateForm, ProfileUpdateForm
from blogs.models import Post
from django.views import View
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):

	if request.method == 'POST':
		form = registerForm(request.POST)
		if form.is_valid():
			new_user = form.save()
			new_user = authenticate(username=form.cleaned_data['username'],password=form.cleaned_data['password1'],)        
			login(request, new_user)
			return HttpResponseRedirect(reverse('blogs:index'))
	else:
		form = registerForm()

	return render(request,'user/register.html',{'form':form})

class profile(View):

	template_name = 'user/profile.html'
	
	def get(self,request,*args,**kwargs):
		# print(self.kwargs['slug'])
		u = User.objects.get(username=self.kwargs['slug'])
		context = {
				'target_user': u,
				'posts':Post.objects.filter(user=u),
		}
		return render(request,self.template_name,context)

@login_required(login_url='/blogs/login/')
def profile_update(request,slug):

	if request.method=='POST':
		
		u_form = UserUpdateForm(request.POST,instance=request.user)
		p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

		if u_form.is_valid() and p_form.is_valid():
			
			u_form.save()
			p_form.save()

			return HttpResponseRedirect(reverse('blogs:profile', args=[request.user.username]))
		
	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = ProfileUpdateForm(instance=request.user.profile)
	
	context = {
		'u_form':u_form,
		'p_form':p_form
	}

	return render(request,'user/profileUpdate.html',context)

user/templates/user/login.html
{% extends "blogs/index.html" %}

{% load crispy_forms_tags %}


{% block content %}
<div style="padding: 2rem;">
<form method="POST" action="{% url 'blogs:login' %}">
		{% csrf_token %}
		<div class="form-control">
			{{form|crispy}}
			<div class="input-group mb-3" style="margin-left: 15px;">
				<input class="btn btn-outline-primary mb-3" type="submit">
				<a href="{% url 'blogs:register' %}" style="margin-left: 15px;"><small>Don't have an account yet?</small></a>
			</div>
		</div>
			
</form>
</div> 
{% endblock %}

user/templates/user/logout.html
{% extends "blogs/index.html" %}

{% load crispy_forms_tags %}


{% block content %}
<div style="padding: 2rem;">
<form method="POST" action="{% url 'blogs:logout' %}">
		{% csrf_token %}
		<div class="form-control">
			<div class="input-group mb-3" style="margin-left: 15px;">
				{{form|crispy}}
			</div>
		</div>
</form>
</div> 
{% endblock %}

user/templates/user/profile.html
{% extends "blogs/leetcode.html" %}

{% block content %}
<div class="profile-wrapper">
	<div class="profile_side" style="padding: 20px;">

		<div class="card mb-3">
			<div class="row g-0">
				<h5 style="padding: 15px">Basic Profile</h5>
			</div>
		  	<div class="row g-0" style="min-height: 100px;">
		    	<div class="col-md-4" style="display: flex;justify-content: center;align-items: center;">
		      		<img src="{{ target_user.profile.image.url}}" style="height: 60%;width: 50%;margin-bottom: 10px;">
		    	</div>
			    <div class="col-md-8">
			      	<div class="card-body">
			        	<h5 class="card-title">{{target_user.username}}</h5>
			        	<p class="card-text"><small class="text-muted">Joined on {{target_user.date_joined | date:'Y-m-d'}}</small></p>
			        	{% if user.is_authenticated and user.username == target_user.username %}
			        	<p class="card-text"><a href="{% url 'blogs:profile-update' user.username %}">Edit?</a></p>
			        	{% endif %}
			      	</div>
			    </div>
		  	</div>
		</div>	

	</div>
	<div class="recent_posts" style="padding: 20px;padding-top: 0px;">
		<div class="list-group">
		  <a href="#" class="list-group-item list-group-item-action disabled" aria-current="true">
		    Recent Blogs
		  </a>
		  {% if posts %}
			  {% for p in posts %}
			  		<a href="{% url 'blogs:post-detail' p.id %}" class="list-group-item list-group-item-action" aria-current="true">
			    		{{p.title}}
			    		<p style="float: right;">{{p.pub_date | date:'Y-m-d H:i'}}</p>
			  		</a>
			  {% endfor %}
		  {% endif %}
		</div>

	</div>
</div>

{% endblock %}

user/templates/user/profileUpdate.html
{% extends "blogs/leetcode.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="profile-update-header" style="height:300px;background:linear-gradient(-150deg, #222222 15%, #373737 70%, #3c4859 94%)">
	<div class="row g-0" style="min-height: 100px;align-items: center;">
    	<div class="col-md-4" style="display: flex;justify-content: center;padding-top: 5%">
      		<img src="{{ user.profile.image.url}}" style="height: 80%;width: 50%;margin-bottom: 10px;">
    	</div>
	    <div class="col-md-8">
	      	<div class="card-body">
	        	<h5 class="card-title" style="color: white">{{user.username}}</h5>
	        	<p class="card-text" style="color: white"><small class="text-muted">Joined on {{user.date_joined | date:'Y-m-d'}}</small></p>
	      	</div>
	    </div>
	</div>
</div>
<div class="profile-update-content">
	<form action="" method="POST" enctype="multipart/form-data">
    	<div class="mb-3">
			{% csrf_token %}
			{{ u_form | crispy}}
			{{ p_form | crispy}}
			<div class="input-group mb-3" style="margin-left: 15px;">
      			<input class="btn btn-outline-primary mb-3" type="submit">
    		</div>
		</div>
	</form>
</div>
{% endblock %}

user/templates/user/register.html
{% extends "blogs/index.html" %}

{% load crispy_forms_tags %}


{% block content %}
<div style="padding: 2rem;">
<form action="{% url 'blogs:register' %}" method="post" id="post_form">
		{% csrf_token %}
		<div class="form-control">
			{{form|crispy}}	
			<div class="input-group mb-3" style="margin-left: 15px;">
				<input class="btn btn-outline-primary mb-3" type="submit">
				<a href="{% url 'blogs:login' %}" style="margin-left: 15px;"><small>Already have an account?</small></a>
			</div>
		</div>
	
		
</form>
</div> 
{% endblock %}